<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\ArenaDomain\ArenaDomain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Dtos\" />
    <Folder Include="IServices\" />
    <Folder Include="Mappers\" />
    <Folder Include="Services\" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
