<Project Sdk="Microsoft.NET.Sdk">

	<ItemGroup>
		<ProjectReference Include="..\ArenaDomain\ArenaDomain.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="FluentValidation" Version="12.1.1" />
		<PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="11.11.0" />

		<PackageReference Include="MailKit" Version="4.16.0" />

		<PackageReference Include="Mapster" Version="10.0.7" />
		<PackageReference Include="Mapster.DependencyInjection" Version="10.0.7" />

		<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.8" />

		<PackageReference Include="Microsoft.IdentityModel.Tokens" Version="8.18.0" />
		<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.18.0" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="Dtos\ProfileDto\" />
		<Folder Include="Interfacees\" />
		<Folder Include="Mappers\" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
	</ItemGroup>

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

</Project>